# Generated by Django 4.1.4 on 2022-12-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owes', models.JSONField(blank=True)),
                ('owed_by', models.JSONField(blank=True)),
                ('balance', models.FloatField(blank=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
    ]
