# Generated by Django 4.1.4 on 2022-12-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='owed_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='owes',
            field=models.JSONField(default=dict),
        ),
    ]
