# Generated by Django 4.1.4 on 2022-12-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_users_balance_alter_users_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
